[DEV] completed debug

diff --git a/Jenkinsfile-VM-DHub-Ansible-CD b/Jenkinsfile-VM-DHub-Ansible-CD
--- a/Jenkinsfile-VM-DHub-Ansible-CD
+++ b/Jenkinsfile-VM-DHub-Ansible-CD
@@ -79,6 +79,16 @@ pipeline {
             ls -al
             ls -al ~/.ssh
 
+            echo "--- Checking known_hosts ---"
+            cat ~/.ssh/known_hosts || echo "known_hosts not found"
+
+            echo "--- Adding vm-lab1 to known_hosts ---"
+            ssh-keyscan -H vm-lab1 >> ~/.ssh/known_hosts
+
+            echo "--- Testing SSH connection ---"
+            ssh -i $SSH_PRIVATE_KEY -o StrictHostKeyChecking=yes vm-lab1 hostname
+
+            echo "--- Running ansible-playbook ---"
             ansible-playbook playbooks/cd/nmf/deploy.yml \
               -i inventory \
               --limit vm-lab1 \
