[DEV] again

diff --git a/Jenkinsfile-VM-DHub-Ansible-CD b/Jenkinsfile-VM-DHub-Ansible-CD
--- a/Jenkinsfile-VM-DHub-Ansible-CD
+++ b/Jenkinsfile-VM-DHub-Ansible-CD
@@ -79,6 +79,12 @@ pipeline {
             ls -al
             ls -al ~/.ssh
 
+            echo "--- Checking known_hosts ---"
+            cat ~/.ssh/known_hosts || echo "known_hosts not found"
+
+            echo "--- Adding 192.168.18.21 to known_hosts ---"
+            ssh-keyscan -H 192.168.18.21 >> ~/.ssh/known_hosts
+
             echo "--- Testing SSH connection ---"
             ssh -i $SSH_PRIVATE_KEY -o StrictHostKeyChecking=yes 192.168.18.21 hostname
 
